<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>CBMFileType</RootNamespace>
    <AssemblyName>CrashdayBitmap.FileType</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Version>1.0.0</Version>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="PaintDotNet.Base">
      <HintPath>$(PaintDotNetPath)/PaintDotNet.Base.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="PaintDotNet.Core">
      <HintPath>$(PaintDotNetPath)/PaintDotNet.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="PaintDotNet.Data">
      <HintPath>$(PaintDotNetPath)/PaintDotNet.Data.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
